# Generated by Django 5.0.1 on 2024-12-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VRV_APP', '0003_alter_userdetails_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdetails',
        ),
    ]
