# Generated by Django 5.0.1 on 2024-12-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VRV_APP', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='status',
            field=models.CharField(blank=True, choices=[('DEACTIVE', 'Deactive'), ('ACTIVE', 'Active')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='token_creation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
